name: Jacoco Demo
run-name: Run tests And Check Coverage

on:
  pull_request:
    # when new or push
    types: [ opened, synchronize ]
    branches:
      # target branches
      - main

jobs:
  run-test-and-check-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21 (Corretto)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Run tests and verify coverage
        run: mvn clean verify




